#!/usr/bin/env bash
# Pasero Copyright (c) 2023-present NAVER Corporation
# Please refer to the license file provided in the project.

set -e

DATA_DIR=data/FLORES
THIS_DIR=`pwd`

if [ -d ${DATA_DIR} ]; then
    exit
fi

function clean {
    python3 -c "import sys; sys.stdout.writelines(' '.join(line.split()) + '\n' for line in sys.stdin)"
}

mkdir -p ${DATA_DIR}
pushd ${DATA_DIR}
wget --trust-server-names https://tinyurl.com/flores200dataset
tar xzf flores200_dataset.tar.gz

for lang in ace_Arab ace_Latn acm_Arab acq_Arab aeb_Arab afr_Latn ajp_Arab aka_Latn als_Latn amh_Ethi apc_Arab arb_Arab arb_Latn ars_Arab ary_Arab arz_Arab asm_Beng ast_Latn awa_Deva ayr_Latn azb_Arab azj_Latn bak_Cyrl bam_Latn ban_Latn bel_Cyrl bem_Latn ben_Beng bho_Deva bjn_Arab bjn_Latn bod_Tibt bos_Latn bug_Latn bul_Cyrl cat_Latn ceb_Latn ces_Latn cjk_Latn ckb_Arab crh_Latn cym_Latn dan_Latn deu_Latn dik_Latn dyu_Latn dzo_Tibt ell_Grek eng_Latn epo_Latn est_Latn eus_Latn ewe_Latn fao_Latn fij_Latn fin_Latn fon_Latn fra_Latn fur_Latn fuv_Latn gaz_Latn gla_Latn gle_Latn glg_Latn grn_Latn guj_Gujr hat_Latn hau_Latn heb_Hebr hin_Deva hne_Deva hrv_Latn hun_Latn hye_Armn ibo_Latn ilo_Latn ind_Latn isl_Latn ita_Latn jav_Latn jpn_Jpan kab_Latn kac_Latn kam_Latn kan_Knda kas_Arab kas_Deva kat_Geor kaz_Cyrl kbp_Latn kea_Latn khk_Cyrl khm_Khmr kik_Latn kin_Latn kir_Cyrl kmb_Latn kmr_Latn knc_Arab knc_Latn kon_Latn kor_Hang lao_Laoo lij_Latn lim_Latn lin_Latn lit_Latn lmo_Latn ltg_Latn ltz_Latn lua_Latn lug_Latn luo_Latn lus_Latn lvs_Latn mag_Deva mai_Deva mal_Mlym mar_Deva min_Arab min_Latn mkd_Cyrl mlt_Latn mni_Beng mos_Latn mri_Latn mya_Mymr nld_Latn nno_Latn nob_Latn npi_Deva nso_Latn nus_Latn nya_Latn oci_Latn ory_Orya pag_Latn pan_Guru pap_Latn pbt_Arab pes_Arab plt_Latn pol_Latn por_Latn prs_Arab quy_Latn ron_Latn run_Latn rus_Cyrl sag_Latn san_Deva sat_Olck scn_Latn shn_Mymr sin_Sinh slk_Latn slv_Latn smo_Latn sna_Latn snd_Arab som_Latn sot_Latn spa_Latn srd_Latn srp_Cyrl ssw_Latn sun_Latn swe_Latn swh_Latn szl_Latn tam_Taml taq_Latn taq_Tfng tat_Cyrl tel_Telu tgk_Cyrl tgl_Latn tha_Thai tir_Ethi tpi_Latn tsn_Latn tso_Latn tuk_Latn tum_Latn tur_Latn twi_Latn tzm_Tfng uig_Arab ukr_Cyrl umb_Latn urd_Arab uzn_Latn vec_Latn vie_Latn war_Latn wol_Latn xho_Latn ydd_Hebr yor_Latn yue_Hant zho_Hans zho_Hant zsm_Latn zul_Latn; do
    clean < flores200_dataset/dev/$lang.dev > FLORES-valid.$lang
    clean < flores200_dataset/devtest/$lang.devtest > FLORES-test.$lang
done

# Create symbolic links to the lang codes used in FLORES-101, M2M-100 or NLE ParaCrawl models.
# FLORES-200 to FLORES-101: afr_Latn,afr amh_Ethi,amh arb_Arab,ara asm_Beng,asm ast_Latn,ast azj_Latn,azj bel_Cyrl,bel ben_Beng,ben bos_Latn,bos bul_Cyrl,bul cat_Latn,cat ceb_Latn,ceb ces_Latn,ces ckb_Arab,ckb cym_Latn,cym dan_Latn,dan deu_Latn,deu ell_Grek,ell eng_Latn,eng est_Latn,est fin_Latn,fin fra_Latn,fra fuv_Latn,ful gle_Latn,gle glg_Latn,glg guj_Gujr,guj hau_Latn,hau heb_Hebr,heb hin_Deva,hin hrv_Latn,hrv hun_Latn,hun hye_Armn,hye ibo_Latn,ibo ind_Latn,ind isl_Latn,isl ita_Latn,ita jav_Latn,jav jpn_Jpan,jpn kam_Latn,kam kan_Knda,kan kat_Geor,kat kaz_Cyrl,kaz kea_Latn,kea khm_Khmr,khm kir_Cyrl,kir kor_Hang,kor lao_Laoo,lao lin_Latn,lin lit_Latn,lit ltz_Latn,ltz lug_Latn,lug luo_Latn,luo lvs_Latn,lav mal_Mlym,mal mar_Deva,mar mkd_Cyrl,mkd mlt_Latn,mlt khk_Cyrl,mon mri_Latn,mri mya_Mymr,mya nld_Latn,nld nob_Latn,nob npi_Deva,npi nso_Latn,nso nya_Latn,nya oci_Latn,oci gaz_Latn,orm ory_Orya,ory pan_Guru,pan pes_Arab,fas pol_Latn,pol por_Latn,por pbt_Arab,pus ron_Latn,ron rus_Cyrl,rus slk_Latn,slk slv_Latn,slv sna_Latn,sna snd_Arab,snd som_Latn,som spa_Latn,spa srp_Cyrl,srp swe_Latn,swe swh_Latn,swh tam_Taml,tam tel_Telu,tel tgk_Cyrl,tgk tgl_Latn,tgl tha_Thai,tha tur_Latn,tur ukr_Cyrl,ukr umb_Latn,umb urd_Arab,urd uzn_Latn,uzb vie_Latn,vie wol_Latn,wol xho_Latn,xho yor_Latn,yor zho_Hans,zho_simpl zho_Hant,zho_trad zsm_Latn,msa zul_Latn,zul
# FLORES-200 to M2M-100: afr_Latn,af amh_Ethi,am arb_Arab,ar ast_Latn,ast azj_Latn,az bak_Cyrl,ba bel_Cyrl,be ben_Beng,bn bos_Latn,bs bul_Cyrl,bg cat_Latn,ca ceb_Latn,ceb ces_Latn,cs cym_Latn,cy dan_Latn,da deu_Latn,de ell_Grek,el eng_Latn,en est_Latn,et fin_Latn,fi fra_Latn,fr fuv_Latn,ff gla_Latn,gd gle_Latn,ga glg_Latn,gl guj_Gujr,gu hat_Latn,ht hau_Latn,ha heb_Hebr,he hin_Deva,hi hrv_Latn,hr hun_Latn,hu hye_Armn,hy ibo_Latn,ig ilo_Latn,ilo ind_Latn,id isl_Latn,is ita_Latn,it jav_Latn,jv jpn_Jpan,ja kan_Knda,kn kat_Geor,ka kaz_Cyrl,kk khm_Khmr,km kor_Hang,ko lao_Laoo,lo lin_Latn,ln lit_Latn,lt ltz_Latn,lb lug_Latn,lg lvs_Latn,lv mal_Mlym,ml mar_Deva,mr mkd_Cyrl,mk plt_Latn,mg khk_Cyrl,mn mya_Mymr,my nld_Latn,nl nob_Latn,no npi_Deva,ne nso_Latn,ns oci_Latn,oc ory_Orya,or pan_Guru,pa pes_Arab,fa pol_Latn,pl por_Latn,pt pbt_Arab,ps ron_Latn,ro rus_Cyrl,ru sin_Sinh,si slk_Latn,sk slv_Latn,sl snd_Arab,sd som_Latn,so spa_Latn,es als_Latn,sq srp_Cyrl,sr ssw_Latn,ss sun_Latn,su swe_Latn,sv swh_Latn,sw tam_Taml,ta tgl_Latn,tl tha_Thai,th tsn_Latn,tn tur_Latn,tr ukr_Cyrl,uk urd_Arab,ur uzn_Latn,uz vie_Latn,vi wol_Latn,wo xho_Latn,xh ydd_Hebr,yi yor_Latn,yo zho_Hans,zh zsm_Latn,ms zul_Latn,zu
# FLORES-200 to ParaCrawl: bul_Cyrl,bg ces_Latn,cs dan_Latn,da deu_Latn,de ell_Grek,el eng_Latn,en est_Latn,et fin_Latn,fi fra_Latn,fr gle_Latn,ga hrv_Latn,hr hun_Latn,hu isl_Latn,is ita_Latn,it lit_Latn,lt lvs_Latn,lv mlt_Latn,mt nld_Latn,nl nob_Latn,nb pol_Latn,pl por_Latn,pt ron_Latn,ro slk_Latn,sk slv_Latn,sl spa_Latn,es swe_Latn,sv
for pair in afr_Latn,af afr_Latn,afr als_Latn,sq amh_Ethi,am amh_Ethi,amh arb_Arab,ar arb_Arab,ara asm_Beng,asm ast_Latn,ast azj_Latn,az azj_Latn,azj bak_Cyrl,ba bel_Cyrl,be bel_Cyrl,bel ben_Beng,ben ben_Beng,bn bos_Latn,bos bos_Latn,bs bul_Cyrl,bg bul_Cyrl,bul cat_Latn,ca cat_Latn,cat ceb_Latn,ceb ces_Latn,ces ces_Latn,cs ckb_Arab,ckb cym_Latn,cy cym_Latn,cym dan_Latn,da dan_Latn,dan deu_Latn,de deu_Latn,deu ell_Grek,el ell_Grek,ell eng_Latn,en eng_Latn,eng est_Latn,est est_Latn,et fin_Latn,fi fin_Latn,fin fra_Latn,fr fra_Latn,fra fuv_Latn,ff fuv_Latn,ful gaz_Latn,orm gla_Latn,gd gle_Latn,ga gle_Latn,gle glg_Latn,gl glg_Latn,glg guj_Gujr,gu guj_Gujr,guj hat_Latn,ht hau_Latn,ha hau_Latn,hau heb_Hebr,he heb_Hebr,heb hin_Deva,hi hin_Deva,hin hrv_Latn,hr hrv_Latn,hrv hun_Latn,hu hun_Latn,hun hye_Armn,hy hye_Armn,hye ibo_Latn,ibo ibo_Latn,ig ilo_Latn,ilo ind_Latn,id ind_Latn,ind isl_Latn,is isl_Latn,isl ita_Latn,it ita_Latn,ita jav_Latn,jav jav_Latn,jv jpn_Jpan,ja jpn_Jpan,jpn kam_Latn,kam kan_Knda,kan kan_Knda,kn kat_Geor,ka kat_Geor,kat kaz_Cyrl,kaz kaz_Cyrl,kk kea_Latn,kea khk_Cyrl,mn khk_Cyrl,mon khm_Khmr,khm khm_Khmr,km kir_Cyrl,kir kor_Hang,ko kor_Hang,kor lao_Laoo,lao lao_Laoo,lo lin_Latn,lin lin_Latn,ln lit_Latn,lit lit_Latn,lt ltz_Latn,lb ltz_Latn,ltz lug_Latn,lg lug_Latn,lug luo_Latn,luo lvs_Latn,lav lvs_Latn,lv mal_Mlym,mal mal_Mlym,ml mar_Deva,mar mar_Deva,mr mkd_Cyrl,mk mkd_Cyrl,mkd mlt_Latn,mlt mlt_Latn,mt mri_Latn,mri mya_Mymr,my mya_Mymr,mya nld_Latn,nl nld_Latn,nld nob_Latn,nb nob_Latn,no nob_Latn,nob npi_Deva,ne npi_Deva,npi nso_Latn,ns nso_Latn,nso nya_Latn,nya oci_Latn,oc oci_Latn,oci ory_Orya,or ory_Orya,ory pan_Guru,pa pan_Guru,pan pbt_Arab,ps pbt_Arab,pus pes_Arab,fa pes_Arab,fas plt_Latn,mg pol_Latn,pl pol_Latn,pol por_Latn,por por_Latn,pt ron_Latn,ro ron_Latn,ron rus_Cyrl,ru rus_Cyrl,rus sin_Sinh,si slk_Latn,sk slk_Latn,slk slv_Latn,sl slv_Latn,slv sna_Latn,sna snd_Arab,sd snd_Arab,snd som_Latn,so som_Latn,som spa_Latn,es spa_Latn,spa srp_Cyrl,sr srp_Cyrl,srp ssw_Latn,ss sun_Latn,su swe_Latn,sv swe_Latn,swe swh_Latn,sw swh_Latn,swh tam_Taml,ta tam_Taml,tam tel_Telu,tel tgk_Cyrl,tgk tgl_Latn,tgl tgl_Latn,tl tha_Thai,th tha_Thai,tha tsn_Latn,tn tur_Latn,tr tur_Latn,tur ukr_Cyrl,uk ukr_Cyrl,ukr umb_Latn,umb urd_Arab,ur urd_Arab,urd uzn_Latn,uz uzn_Latn,uzb vie_Latn,vi vie_Latn,vie wol_Latn,wo wol_Latn,wol xho_Latn,xh xho_Latn,xho ydd_Hebr,yi yor_Latn,yo yor_Latn,yor zho_Hans,zh zho_Hans,zho_simpl zho_Hant,zho_trad zsm_Latn,ms zsm_Latn,msa zul_Latn,zu zul_Latn,zul; do
    orig=$( echo $pair | cut -d',' -f1 )
    dest=$( echo $pair | cut -d',' -f2 )
    ln -s FLORES-valid.$orig FLORES-valid.$dest
    ln -s FLORES-test.$orig FLORES-test.$dest
done

rm -r flores200_dataset
popd
